[package]
name = "rust_bevy_plumbing"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.2"
bevy_2d_line = "0.1.4"
rand = "0.9.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
